// <auto-generated />
namespace OnlineAuction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fix_AuctionDel_Field_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_AuctionDel_Field_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "202009021457201_fix_Auction-Del_Field_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
