// <auto-generated />
namespace OnlineAuction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AuctionAdd_Field_Descript : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuctionAdd_Field_Descript));
        
        string IMigrationMetadata.Id
        {
            get { return "202009051613101_Auction-Add_Field_Descript"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
