// <auto-generated />
namespace OnlineAuction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fix_Auctionadd_field_Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_Auctionadd_field_Product));
        
        string IMigrationMetadata.Id
        {
            get { return "202009021505346_fix_Auction-add_field_Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
