// <auto-generated />
namespace OnlineAuction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fix_accountAdd_field_balance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_accountAdd_field_balance));
        
        string IMigrationMetadata.Id
        {
            get { return "202009031153081_fix_account-Add_field_balance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
